[package]
name = "rikiki"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rikiki"
path = "bin/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
strum_macros = "0.26"
